### PR TITLE
Don't escape brackets in code in Quickbook output

### LINKED ISSUE #69: Overzealous escaping
(in Quickbook). Fix is in progress. See https://www.boost.org/doc/libs/1_76_0/libs/json/doc/html/json/ref/boost__json__object/operator_lb__rb_.html

```
operator\[\](
```

Might be due to a recent regression.

From Vinnie:
"I think the rule is, you need to escape unless you are in a code block (backticks)
or the triple backtick delimiter"

### PR DESCRIPTION
**Pull request by evanlenz**
fix #69

### CODE REVIEW

**Comment by evanlenz** [comment]
@madmongo1 This pull request replaces #71, using just one commit (after fixing the regression I noticed). There was probably a simpler way to do this; sorry for the noise.

**Comment by vinniefalco** [comment]
@grisumbras please check the output of Boost.JSON's docs with these changes

**Comment by madmongo1** [comment]
> @madmongo1 This pull request replaces #71, using just one commit (after fixing the regression I noticed). There was probably a simpler way to do this; sorry for the noise.

No worries. I'll run try again.

**Comment by grisumbras** [comment]
I've tried this branch on JSON and it does fix the issue.

**Comment by madmongo1** [comment]
please go ahead and rebase

**Pull request merged**
