### PR TITLE
Group overloads by briefdescription without requiring them to be adjacent

### LINKED ISSUE #44: Constructors with the same brief are not always grouped together
image

### PR DESCRIPTION
**Pull request by evanlenz**
This fixes #44. (The C++ may also need some javadoc comments added to the two constructors grouped under the currently-blank heading.)

### CODE REVIEW

**Comment by vinniefalco** [comment]
One of the briefs is still missing:
image

**Comment by vinniefalco** [comment]
The groups are together and share the brief, but there are two light gray bounding boxes. I guess we can live with that:
image

**Comment by evanlenz** [comment]
Ah, I missed the second bullet point. I'll address that as well.

As for the space between the bounding boxes, that is due to the empty briefdescription for those two constructors. It works out sort of okay in this situation, but we shouldn't live with it, because it might not be pseudo-grouped appropriately next time.

**Comment by vinniefalco** [comment]
I think this whole thing should be squashed down to one commit, and in the commit description you can put a bulleted list of things changed (i.e. the text from the individual commits).

Rationale: If you look at the total changes, it is very little overall change, and it is easier to comprehend the set of changes as one diff instead of three. Up to you though, whatever is easier to maintain.

**Comment by evanlenz** [comment]
I squashed it down to two commits, one for each fix on a different page.

**Comment by vinniefalco** [comment]
Sensible

**Comment by vinniefalco** [comment]
`DISTRIBUTE_GROUP_DOC` needs to be documented, I will add it to README.md

**Pull request closed without merging**
