### PR TITLE
Fix up bad enum-value link targets from Doxygen

### LINKED ISSUE #70: Link to wrong enum page
Fix is in progress but outcome is uncertain. See https://www.boost.org/doc/libs/1_75_0/libs/beast/doc/html/beast/ref/boost__beast__http__message/result/overload1.html

`static::unknown` erroneously links to `http::field` (which has `unknown` as one of its values).

This is due to a bad link being output by Doxygen. However, we may be able to use an appropriate heuristic. See the **d:get-target-element()** function in base-extract-xml-pages.xsl

### PR DESCRIPTION
**Pull request by evanlenz**
Fix #70

### CODE REVIEW

**Comment by evanlenz** [comment]
Is there anything in particular that's holding up this fix?

**Comment by vinniefalco** [comment]
Good question. @madmongo1 ? Does this fix the enums?

**Comment by madmongo1** [comment]
In the documentation of `doc/html/beast/ref/boost__beast__http__message/result/overload1.html` the `status::unknown` does not link to anything (it is not emitted as a hyperlink).

However, tracking through to the base class documentation at `doc/html/beast/ref/boost__beast__http__header/result/overload1.html`, `status::unknown` is emitted as a hyperlink to `doc/html/beast/ref/boost__beast__http__status.html` (which seems correct).

Is this the intended behaviour?
@evanlenz

**Comment by madmongo1** [comment]
missing-link

**Comment by vinniefalco** [comment]
@madmongo1 it looks like you don't have the boost docbook templates installed

**Comment by vinniefalco** [comment]
It seems like it used to work and now it doesn't?

**Comment by madmongo1** [comment]
> @madmongo1 it looks like you don't have the boost docbook templates installed

I take it that this is the reason for the lack of formatting? 
I've often wondered about that.

**Comment by evanlenz** [comment]
> It seems like it used to work and now it doesn't?

That is indeed what it seems. But I will try to reproduce. It should produce a link (the right one!).

**Comment by evanlenz** [comment]
@madmongo1 It works for me. When I switch docca to branch issue70-link-to-wrong-enum-page and run `b2 clean` followed by `b2` in the libs/beast/doc directory, it produces the result I expect:

image

The "status::unknown" link takes me to this page: file:///C:/cygwin64/home/evanl/boost/libs/beast/doc/html/beast/ref/boost__beast__http__status.html

**Comment by madmongo1** [comment]
I rebased develop onto the pr branch before running the test. I wonder if that’s relevant.
In any case, will retest.

**Comment by evanlenz** [comment]
It might be! The link might be getting disappeared somehow from the more recent fix. I'm just speculating though.

This is a case where the XSLT visualization/debug option would come in very handy! :-) @grisumbras

**Comment by evanlenz** [comment]
I tried rebasing develop onto the pr branch as well just now, and it didn't make a difference (still works for me).

**Comment by madmongo1** [comment]
Ok great. Will clean and rebuild

**Comment by madmongo1** [comment]
Confirmed correct on second attempt.

**Comment by madmongo1** [comment]
rebased to develop

**Pull request closed without merging**
