### PR TITLE
Support doxygen 1.9.7

### PR DESCRIPTION
**Pull request by sdkrystian**

### CODE REVIEW

**Comment by alandefreitas** [comment]
I guess this obsoletes #140. We can actually put everything in a single PR that fixes the transition from 1.8.15 to 1.9.7.

Just tested this locally. So this fixes errors like

```
Error: no ID for constraint linkend: "url.ref.boost__urls__url_view_base.url_view".
```

but we still have 

```
bin.v2/libs/url/doc/reference.qbk:65373: warning: in column:69, unexpected character: `
```

which is having a big impact on the docs, since most pages have links in the javadoc details. Many of the autolinks in the BNF might be just wrong but the ones in the examples are usually not.

I can see how autolink is *related* to the issue in the sense that there would be no broken links if there were links there. But I can't see why autolink would be *causing* the issue even if it's a good idea to remove it (we'd have to think about the examples) since doxygen 1.8.15 did work OK with the links it generated.

**Comment by alandefreitas** [comment]
Updating the problem...

docca generates this via doxygen 1.9.7

```
assert( ! [link url.ref.boost__urls__grammar__ci_is_less `ci_is_less`]( "Boost" , "boost" ) );
```

and this via doxygen 1.8.15

```
assert( ! ci_is_less( "Boost", "boost" ) );
```

Maybe this has less to do with docca and doxygen 1.8.15 just doesn't enable auto-linking by default?

**Review by alandefreitas — COMMENTED** [review]
I think this is good to go as long as code blocks don't support links.

I don't even like that pattern that much, but could you capitalize the commit messages to match the rest of the project and change the latest to commit to reflect it's no longer a workaround?

Some of the messages are also not as descriptive now that we understand the cause of the issues. It could be something like:

- Code blocks don't include links
- Suppress private friends in ____
- Support operator IDs with extra spaces

(The last one is because the thing is already backward compatible... the commit is actually making it "forward" compatible with the new versions, so it's just supporting something else.)

**Comment by alandefreitas** [comment]
> I think this is good to go as long as code blocks don't support links.

OK... So "``" fixes this. And we have a problem with private friends again. :neutral_face:

**Comment by alandefreitas** [comment]
Also the problem with AUTOLINK_SUPPORT not being enforced seems to come from here:

https://github.com/boostorg/docca/blob/8e2c71d2ea84f45016af02162a87790872e22a45/docca.jam#L44-L51

**Comment by sdkrystian** [comment]
> Also the problem with AUTOLINK_SUPPORT not being enforced seems to come from here:
> 
> https://github.com/boostorg/docca/blob/8e2c71d2ea84f45016af02162a87790872e22a45/docca.jam#L44-L51

Already tried setting `AUTOLINK_SUPPORT=OFF` there & it had no effect

**Comment by alandefreitas** [comment]
> Already tried setting AUTOLINK_SUPPORT=OFF there & it had no effect

Yes. This thing has many points of failure and each test takes a few minutes, which is annoying.

**Pull request merged**
