### PR TITLE
Docca jam module

### PR DESCRIPTION
**Pull request by grisumbras**

### CODE REVIEW

**Comment by grisumbras** [comment]
@vinniefalco @evanlenz This is what I have so far.
I'm planning to investigate whether I can move `index.xml` generation into `docca.jam` too.

**Comment by vinniefalco** [comment]
squash, dawg

**Comment by evanlenz** [comment]
This looks really promising! And I appreciate the granular commits (at least for interim, pre-squash grokking).

Let me know if you'd also be interested in issue #66, which I just created. I can't remember if there was anything special about the existing docca build output that the visualization build depended on, but I will be anxious to look into this.

**Comment by grisumbras** [comment]
@vinniefalco So, this is what I ended up with. Check out example/Jamfile for new usage.
In short, `docca.reference` produces a qbk file from a bunch of C++ headers. The headers (and `<doxygen:param>` properties) are used to generate an intermediary Doxygen config file, then Doxygen is launched, then docca's stylesheets are applied.

The main difference with the status quo is that instead of putting Doxygen configuration into a doxyfile you should use target properties.

**Comment by grisumbras** [comment]
Oh, one other change could also be made. I can probably b2's type coversion mechanism to allow this:
```
qbk reference : xsl/custom-overrides.xsl [ glob sources ] : <doxygen:param>X=Y … ;
```
I don't know if there's any need for that, though.

**Comment by vinniefalco** [comment]
This looks good, and come to think of it, it is fine not to squash it if you want to keep individual commits. I would ask @pdimov to have a look to see if there is anything which is non-idiomatic or would cause problems with the building of releases. You can merge it when you like, but please make sure its a fast-forward and not a merge commit.

**Comment by pdimov** [comment]
Looks good to me. If it causes any problems there's plenty of time to fix it.

**Comment by evanlenz** [comment]
I'm not sure if I'm doing something wrong, but I get the following when I try to run b2 in the example directory:

```
Performing configuration checks

    - default address-model    : 32-bit (cached)
    - default architecture     : x86 (cached)
    - symlinks supported       : no  (cached)
    - junctions supported      : yes (cached)
    - hardlinks supported      : yes (cached)
error: Unable to find file or target named
error:     '_reference-dir/extract-xml-pages.xsl'
error: referred to from project at
error:     '.'
```

I'm looking forward to seeing this work, because it looks like an awesome improvement to me!

**Comment by grisumbras** [comment]
@evanlenz just so I could test it, how do you run b2? From what directory, inside boost or not?

**Comment by evanlenz** [comment]
I run it from the Cygwin command line:

```
evanl@THINKPAD-T480 ~/boost/tools/docca/example
$ which b2
/home/evanl/boost/b2

evanl@THINKPAD-T480 ~/boost/tools/docca/example
$ b2 -v
B2 Version 4.3. OS=NT.
  Copyright 1993-2002 Christopher Seiwald and Perforce Software, Inc.
  Copyright 2001 David Turner.
  Copyright 2001-2004 David Abrahams.
  Copyright 2002-2019 Rene Rivera.
  Copyright 2003-2015 Vladimir Prus.

  DEFAULTS: jobs = 8

evanl@THINKPAD-T480 ~/boost/tools/docca/example
$ b2
Performing configuration checks

    - default address-model    : 32-bit (cached)
    - default architecture     : x86 (cached)
    - symlinks supported       : no  (cached)
    - junctions supported      : yes (cached)
    - hardlinks supported      : yes (cached)
error: Unable to find file or target named
error:     '_reference-dir/extract-xml-pages.xsl'
error: referred to from project at
error:     '.'
```

**Comment by grisumbras** [comment]
I  tried building from `example` directory locally, but that error does not happen for me. So, this is possibly due to either Windows or Cygwin. Sadly, I know absolutely nothing about Cygwin. @pdimov I remember you using Cygwin. Can you please test the branch on your machine?

**Comment by vinniefalco** [comment]
Could this be a problem with relative paths?

**Comment by grisumbras** [comment]
@evanlenz please pull the updates for the branch and try again.

**Comment by evanlenz** [comment]
That did the trick. Thank you!

**Comment by grisumbras** [comment]
Thans to @pdimov for helping me with investigating this bug.

**Comment by grisumbras** [comment]
So, now that everything is good, I'll squash it and merge into develop?

**Comment by evanlenz** [comment]
It sounded like @vinniefalco was okay with keeping the granular commits. If that’s still true, keeping the granular commits would be my preference. Not that I exactly want to be on the hook for learning bjam, but I did find your commits helpful for learning!

**Pull request merged**
